### ISSUE TITLE
numpy==1.22.4 scipy==1.8.1 requirements

### ISSUE THREAD

**Issue by WASasquatch** [tdh8316/triangler#10]
**Is your feature request related to a problem? Please describe.**
Currently triangler requires numpy==1.22.4 scipy==1.8.1, or it won't run, but the systems I want to use it in require later versions of both numpy and scipy. 

**Describe the solution you'd like**
Anyway you could adopt your functions to operate with more general or later versions?

**Comment by tdh8316** [comment]
Hi, thanks for opening the issue. I'll check for compatibility with numpy and scipy.
But unfortunately, it can be delayed, since I'm currently overwhelmed with my jobs.

Best!

**Comment by tdh8316** [comment]
It is fixed at a commit 3be2fdd0d38cdcf82e772051e92b32c7601da703 and triangler is working with the latest version of numpy and scipy!
I just tested triangler with numpy 1.24.3 and scipy 1.10.1 which are the latest versions.

Thank you for letting me know.
Have a good day!

**Comment by WASasquatch** [comment]
Thank you for getting time to do this! It's much appreciated.
